"""Docket templates, scenario rules, and governance catalogs."""

from __future__ import annotations

from ..models import *

TEMPLATES: dict[str, DocketTemplate] = {
    "connector_corridor": DocketTemplate(
        "connector_corridor",
        "Connector Corridor Pilot",
        "transit",
        "LINE",
        {"activity": 5, "exposure": -2, "friction": 2},
        {"activity": 2, "exposure": -1, "friction": 1},
        money_cost=24,
        mitigation_cost=10,
        expiration_policy="city_momentum",
        pressure_category="transit",
        preview="Improves access between two districts. Adds a new line with some access and exposure tradeoffs.",
        inspect_hint="Ridership estimates support the route. Several alignment objections are already on file.",
        target_rule="Select exactly two districts to connect.",
        stakeholder="transit_authority",
        failure_mode="construction delay",
        failure_effects={"friction": 3, "exposure": 2, "activity": -2},
        failure_base_chance=0.22,
        good_fit_types=("mercantile", "civic"),
        bad_fit_types=("residential", "natural"),
        supporter_groups=("commuters", "workers", "developers"),
        concerned_groups=("homeowners", "elders", "conservationists"),
        growth_groups=("commuters", "workers"),
        contact_name="Transit Alignment Office",
        spawn_archetype_id="connector_corridor",
    ),
    "procession_route": DocketTemplate(
        "procession_route",
        "Licensed Procession Route",
        "event",
        "LINE",
        {"trust": 8, "activity": 2, "friction": 3, "exposure": 1},
        {"trust": 2, "friction": 1},
        money_cost=10,
        mitigation_cost=8,
        expires_after=1,
        expiration_policy="missed_window",
        pressure_category="event",
        preview="Adds a temporary event route. Trust may improve, but crowd control needs review.",
        inspect_hint="Route review found strong interest, likely bottlenecks, and signage conflicts.",
        target_rule="Select exactly two districts for the route endpoints.",
        stakeholder="celebrants",
        denial_heat=2,
        failure_mode="crowd-control miss",
        failure_effects={"friction": 3, "exposure": 3, "trust": -1},
        failure_base_chance=0.24,
        good_fit_types=("civic", "academic", "mercantile"),
        bad_fit_types=("industrial", "natural"),
        supporter_groups=("artists", "students", "vendors"),
        concerned_groups=("commuters", "elders", "civil_servants"),
        growth_groups=("artists", "vendors"),
        contact_name="Event Route Office",
        spawn_archetype_id="licensed_procession",
    ),
    "utility_expansion_trench": DocketTemplate(
        "utility_expansion_trench",
        "Utility Expansion Trench",
        "utility",
        "LINE",
        {"exposure": -6, "activity": 2, "friction": 2},
        {"exposure": -2, "friction": 1},
        money_cost=22,
        mitigation_cost=8,
        expiration_policy="momentum_with_followup_risk",
        pressure_category="utility",
        preview="Reduces infrastructure exposure and improves utility service coverage.",
        inspect_hint="Utility maps mostly agree, but one key segment still needs field confirmation.",
        target_rule="Select exactly two districts crossed by the utility work.",
        stakeholder="utility_board",
        ignore_heat=2,
        failure_mode="service outage",
        failure_effects={"exposure": 5, "friction": 2, "activity": -1},
        failure_base_chance=0.25,
        good_fit_types=("industrial", "civic"),
        bad_fit_types=("residential", "natural"),
        supporter_groups=("families", "workers", "civil_servants"),
        concerned_groups=("commuters", "vendors", "homeowners"),
        growth_groups=("workers",),
        contact_name="Utility Review Office",
        spawn_archetype_id="utility_trench",
    ),
    "natural_reserve_conversion": DocketTemplate(
        "natural_reserve_conversion",
        "Natural Reserve Conversion",
        "land",
        "POLYGON",
        {"trust": 5, "exposure": -4, "activity": -2, "friction": 1},
        {"trust": 2, "exposure": -1, "activity": -1},
        money_cost=12,
        mitigation_cost=5,
        expiration_policy="missed_window",
        pressure_category="land",
        preview="Creates a protected area and lowers hazard pressure through green-buffer coverage.",
        inspect_hint="Boundary materials are mostly complete. One edge may need legal review.",
        target_rule="Select one or more districts proposed for reserve status.",
        stakeholder="conservation_trust",
        denial_heat=2,
        failure_mode="boundary dispute",
        failure_effects={"friction": 3, "exposure": 2, "trust": -2},
        failure_base_chance=0.20,
        good_fit_types=("natural", "academic"),
        bad_fit_types=("industrial", "mercantile"),
        supporter_groups=("conservationists", "artists", "elders"),
        concerned_groups=("developers", "workers", "commuters"),
        growth_groups=("conservationists",),
        decline_groups=("developers",),
        contact_name="Reserve Boundary Office",
        spawn_archetype_id="protected_reserve",
    ),
    "mixed_use_rezoning": DocketTemplate(
        "mixed_use_rezoning",
        "Mixed-Use Rezoning Petition",
        "development",
        "POLYGON",
        {"activity": 6, "friction": 3, "exposure": 2, "trust": 1},
        {"activity": 2, "friction": 1},
        money_cost=16,
        mitigation_cost=9,
        expiration_policy="city_momentum",
        pressure_category="development",
        preview="Adds growth pressure and tax base; neighborhood fit and service capacity are uncertain.",
        inspect_hint="Applicant submitted renderings, loading plans, and a service-capacity statement.",
        target_rule="Select one or more districts to rezone.",
        stakeholder="developers",
        denial_heat=2,
        failure_mode="zoning appeal",
        failure_effects={"friction": 4, "exposure": 1, "activity": -2},
        failure_base_chance=0.23,
        good_fit_types=("residential", "mercantile"),
        bad_fit_types=("natural", "civic"),
        supporter_groups=("developers", "workers", "commuters"),
        concerned_groups=("renters", "homeowners", "conservationists"),
        growth_groups=("renters", "workers", "commuters"),
        decline_groups=("conservationists",),
        contact_name="Rezoning Applicant",
        spawn_archetype_id="mixed_use_overlay",
    ),
    "child_development_park_annex": DocketTemplate(
        "child_development_park_annex",
        "Child Development Park Annex",
        "education",
        "POINT",
        {"trust": 5, "exposure": -3, "friction": -1, "activity": 1},
        {"trust": 1, "exposure": -1},
        money_cost=18,
        mitigation_cost=6,
        expiration_policy="missed_window",
        pressure_category="service",
        preview="Adds a family-service annex. Child-service coverage and local exposure should improve.",
        inspect_hint="Need is clear. Staffing plan is still provisional.",
        target_rule="Select exactly one district for the annex.",
        stakeholder="families",
        denial_heat=2,
        failure_mode="staffing shortfall",
        failure_effects={"exposure": 3, "friction": 2, "trust": -1},
        failure_base_chance=0.18,
        good_fit_types=("residential", "academic", "civic"),
        bad_fit_types=("industrial",),
        supporter_groups=("families", "elders", "civil_servants"),
        concerned_groups=("commuters", "homeowners"),
        growth_groups=("families",),
        contact_name="Child Services Office",
        spawn_archetype_id="child_service_annex",
    ),
    "street_vendor_compact": DocketTemplate(
        "street_vendor_compact",
        "Street Vendor Compact",
        "business",
        "POINT",
        {"activity": 6, "trust": 4, "friction": 2, "exposure": 1},
        {"activity": 2, "trust": 1, "friction": 1},
        money_cost=12,
        mitigation_cost=6,
        expiration_policy="momentum_with_followup_risk",
        pressure_category="business",
        preview="Creates a small-commerce point. Mitigation can reduce nuisance and spillover issues.",
        inspect_hint="Public comments mention foot traffic, late hours, and food-service concerns.",
        target_rule="Select exactly one host district.",
        stakeholder="vendors",
        denial_heat=2,
        ignore_heat=2,
        failure_mode="unlicensed spillover",
        failure_effects={"friction": 3, "exposure": 2, "activity": -1},
        failure_base_chance=0.22,
        good_fit_types=("mercantile", "residential"),
        bad_fit_types=("civic", "natural"),
        supporter_groups=("vendors", "artists", "students"),
        concerned_groups=("homeowners", "civil_servants", "commuters"),
        growth_groups=("vendors", "artists"),
        contact_name="Vendor Compact Office",
        spawn_archetype_id="vendor_market",
    ),
    "business_license_fee_sweep": DocketTemplate(
        "business_license_fee_sweep",
        "Business License Fee Sweep",
        "business",
        "POINT",
        {"activity": 2, "exposure": -1, "friction": 1},
        {"activity": 1},
        money_cost=4,
        mitigation_cost=3,
        expires_after=1,
        expiration_policy="missed_window",
        pressure_category="business",
        preview="Collects overdue license fees from a commercial node. May recover money and raise some local concern.",
        inspect_hint="License records are complete, and several renewals are ready for payment.",
        target_rule="Select exactly one district with visible business activity.",
        stakeholder="vendors",
        denial_heat=1,
        ignore_heat=2,
        failure_mode="fee protest",
        failure_effects={"friction": 3, "activity": -1},
        failure_base_chance=0.14,
        good_fit_types=("mercantile", "civic", "industrial"),
        bad_fit_types=("natural",),
        supporter_groups=("civil_servants", "workers"),
        concerned_groups=("vendors", "homeowners"),
        growth_groups=("civil_servants",),
        contact_name="Revenue Review Office",
        spawn_archetype_id="license_fee_counter",
    ),
    "contractor_renovation_waiver": DocketTemplate(
        "contractor_renovation_waiver",
        "Contractor Renovation Waiver",
        "residential",
        "POINT",
        {"activity": 4, "exposure": 3, "friction": 1},
        {"friction": 1, "exposure": 1},
        money_cost=14,
        mitigation_cost=7,
        expiration_policy="momentum_with_followup_risk",
        pressure_category="construction",
        preview="Speeds a residential project. Contractor reliability and inspection demand need review.",
        inspect_hint="Contractor history is mixed, with several projects requiring follow-up inspection.",
        target_rule="Select exactly one district containing the work.",
        stakeholder="contractors",
        ignore_heat=2,
        failure_mode="inspection failure",
        failure_effects={"exposure": 6, "friction": 2, "activity": -2},
        failure_base_chance=0.28,
        good_fit_types=("residential", "mercantile"),
        bad_fit_types=("natural", "academic"),
        supporter_groups=("homeowners", "developers", "workers"),
        concerned_groups=("renters", "elders"),
        growth_groups=("homeowners", "developers"),
        decline_groups=("renters",),
        contact_name="Contractor Permit Office",
        spawn_archetype_id="renovation_site",
    ),
    "fire_budget_escalation": DocketTemplate(
        "fire_budget_escalation",
        "Fire Department Budget Escalation",
        "department",
        "POLYGON",
        {"exposure": -7, "friction": -1, "activity": -2},
        {"exposure": -2},
        money_cost=20,
        mitigation_cost=5,
        expiration_policy="mandatory_followup",
        pressure_category="safety",
        preview="Adds fire-response coverage and lowers exposure exposure.",
        inspect_hint="Incident trends support the request. Equipment scope should still be reviewed.",
        target_rule="Select one or more districts covered by the budget request.",
        stakeholder="fire_department",
        denial_heat=3,
        ignore_heat=2,
        failure_mode="coverage gap",
        failure_effects={"exposure": 4, "friction": 2},
        failure_base_chance=0.16,
        good_fit_types=("industrial", "civic", "residential"),
        bad_fit_types=("natural",),
        supporter_groups=("civil_servants", "families", "workers"),
        concerned_groups=("developers", "conservationists"),
        growth_groups=("civil_servants",),
        contact_name="Fire Budget Office",
        spawn_archetype_id="fire_coverage_area",
    ),
    "public_art_museum_grant": DocketTemplate(
        "public_art_museum_grant",
        "Public Art and Museum Grant",
        "culture",
        "POINT",
        {"trust": 7, "activity": 1, "friction": 1},
        {"trust": 2},
        money_cost=15,
        mitigation_cost=6,
        expiration_policy="missed_window",
        pressure_category="culture",
        preview="Raises the local cultural profile. Public response may vary by district.",
        inspect_hint="Museum finances are stable. Project scope and duration still need confirmation.",
        target_rule="Select exactly one district for the grant site.",
        stakeholder="arts_council",
        failure_mode="procurement scandal",
        failure_effects={"friction": 3, "trust": -3, "activity": -1},
        failure_base_chance=0.20,
        good_fit_types=("civic", "academic", "mercantile"),
        bad_fit_types=("industrial",),
        supporter_groups=("artists", "students", "vendors"),
        concerned_groups=("civil_servants", "homeowners"),
        growth_groups=("artists", "students"),
        contact_name="Arts Grant Office",
        spawn_archetype_id="museum_grant_site",
    ),
    ENFORCEMENT_TEMPLATE_ID: DocketTemplate(
        ENFORCEMENT_TEMPLATE_ID,
        "Unpermitted Follow-Through",
        "enforcement",
        "POINT",
        {"exposure": -3, "friction": 2, "activity": -1},
        {"friction": 1},
        money_cost=8,
        mitigation_cost=6,
        expiration_policy="mandatory_followup",
        pressure_category="enforcement",
        preview="A previously rejected or ignored request appears to have moved ahead without approval.",
        inspect_hint="Compliance photos support the case, but timestamps need verification.",
        target_rule="Select exactly one district where the unpermitted work or event is visible.",
        stakeholder="general_public",
        denial_heat=2,
        ignore_heat=2,
        is_enforcement=True,
        supporter_groups=("civil_servants", "homeowners"),
        concerned_groups=("vendors", "renters", "workers"),
        contact_name="Compliance Inspector",
        spawn_archetype_id="compliance_case",
    ),
    "compliance_settlement_drive": DocketTemplate(
        "compliance_settlement_drive",
        "Compliance Settlement Drive",
        "compliance",
        "POINT",
        {"exposure": -2, "friction": -1, "activity": -1},
        {"exposure": -1},
        money_cost=3,
        mitigation_cost=4,
        expires_after=1,
        expiration_policy="missed_window",
        pressure_category="compliance",
        preview="Converts low-grade violations into payment plans. Helps revenue but does not remove all compliance exposure.",
        inspect_hint="Most parties are willing to settle if payment terms are clear.",
        target_rule="Select exactly one district with an active compliance backlog.",
        stakeholder="compliance_office",
        denial_heat=1,
        ignore_heat=2,
        failure_mode="missed settlement window",
        failure_effects={"friction": 2, "exposure": 2},
        failure_base_chance=0.16,
        good_fit_types=("mercantile", "industrial", "residential"),
        bad_fit_types=("natural",),
        supporter_groups=("civil_servants", "families"),
        concerned_groups=("vendors", "developers", "workers"),
        growth_groups=("civil_servants",),
        contact_name="Settlement Officer",
        spawn_archetype_id="settlement_agreement",
    ),
    CIVIC_INCIDENT_TEMPLATE_ID: DocketTemplate(
        CIVIC_INCIDENT_TEMPLATE_ID,
        "Civic Incident Response",
        "incident",
        "POINT",
        {"friction": -2, "exposure": -1, "activity": -1},
        {"friction": -1},
        money_cost=9,
        mitigation_cost=7,
        expiration_policy="mandatory_followup",
        pressure_category="incident",
        preview="A local grievance has become a visible incident and needs a response.",
        inspect_hint="Complaint packet includes signatures, maps, and prior correspondence.",
        target_rule="Select exactly one district where the civic incident is visible.",
        stakeholder="general_public",
        denial_heat=1,
        ignore_heat=2,
        is_incident=True,
        supporter_groups=("civil_servants",),
        concerned_groups=("families", "workers", "renters", "vendors"),
        contact_name="Incident Intake Office",
        spawn_archetype_id="civic_incident_marker",
    ),
    "bus_priority_link": DocketTemplate(
        "bus_priority_link",
        "Bus Priority Link",
        "transit",
        "LINE",
        {"activity": 3, "exposure": -1, "friction": 1},
        {"activity": 1, "exposure": -1},
        money_cost=18,
        mitigation_cost=6,
        expiration_policy="city_momentum",
        pressure_category="transit",
        preview="Adds a bus-priority segment. Mobility improves, but curb access concerns are likely.",
        inspect_hint="Transit staff support the signal-priority plan. Curb impacts need review.",
        target_rule="Select exactly two districts for link endpoints.",
        stakeholder="transit_authority",
        failure_mode="curb-management dispute",
        failure_effects={"friction": 2, "activity": -1},
        failure_base_chance=0.16,
        good_fit_types=("mercantile", "civic", "academic"),
        bad_fit_types=("natural",),
        supporter_groups=("commuters", "workers", "students"),
        concerned_groups=("homeowners", "vendors"),
        growth_groups=("commuters", "workers"),
        contact_name="Transit Signal Office",
        spawn_archetype_id="bus_priority_link",
        scenario_tags=("port_boom",),
    ),
    "water_main_loop": DocketTemplate(
        "water_main_loop",
        "Water Main Loop",
        "utility",
        "LINE",
        {"exposure": -5, "activity": 1, "friction": 1},
        {"exposure": -2},
        money_cost=24,
        mitigation_cost=8,
        expiration_policy="momentum_with_followup_risk",
        pressure_category="utility",
        preview="Loops water service between districts. Lowers flood and fire exposure if construction is managed well.",
        inspect_hint="Hydraulic notes are complete. Valve coordination still needs review.",
        target_rule="Select exactly two districts for the loop endpoints.",
        stakeholder="utility_board",
        failure_mode="valve coordination miss",
        failure_effects={"exposure": 4, "friction": 2},
        failure_base_chance=0.18,
        good_fit_types=("industrial", "civic", "residential"),
        bad_fit_types=("natural",),
        supporter_groups=("families", "workers", "civil_servants"),
        concerned_groups=("commuters", "homeowners"),
        growth_groups=("workers",),
        contact_name="Water Systems Office",
        spawn_archetype_id="water_main_loop",
        scenario_tags=("port_boom",),
    ),
    "green_buffer_reserve": DocketTemplate(
        "green_buffer_reserve",
        "Green Buffer Reserve",
        "land",
        "POLYGON",
        {"trust": 4, "exposure": -4, "activity": -1},
        {"trust": 1, "exposure": -1},
        money_cost=14,
        mitigation_cost=5,
        expiration_policy="missed_window",
        pressure_category="land",
        preview="Creates a planted buffer that absorbs heat, noise, and ecological pressure.",
        inspect_hint="Planting plan is workable. Maintenance funding still needs confirmation.",
        target_rule="Select one or more districts for the reserve boundary.",
        stakeholder="conservation_trust",
        failure_mode="maintenance shortfall",
        failure_effects={"exposure": 2, "friction": 1, "trust": -1},
        failure_base_chance=0.14,
        good_fit_types=("natural", "residential", "academic"),
        bad_fit_types=("industrial",),
        supporter_groups=("conservationists", "families", "elders", "artists"),
        concerned_groups=("developers", "workers"),
        growth_groups=("conservationists", "artists"),
        decline_groups=("developers",),
        contact_name="Green Buffer Office",
        spawn_archetype_id="green_buffer_reserve",
        scenario_tags=("garden_city",),
    ),
    "inspection_order": DocketTemplate(
        "inspection_order",
        "Inspection Order",
        "compliance",
        "POINT",
        {"exposure": -3, "friction": 1},
        {"exposure": -1},
        money_cost=8,
        mitigation_cost=4,
        expiration_policy="mandatory_followup",
        pressure_category="inspection",
        preview="Orders a compliance inspection. Pollution, fire, and noise risks may drop after field review.",
        inspect_hint="Inspector availability is confirmed for this order.",
        target_rule="Select exactly one district for the inspection order.",
        stakeholder="compliance_office",
        failure_mode="missed inspection window",
        failure_effects={"exposure": 2, "friction": 1},
        failure_base_chance=0.12,
        supporter_groups=("families", "elders", "civil_servants"),
        concerned_groups=("vendors", "developers", "workers"),
        contact_name="Inspection Office",
        spawn_archetype_id="inspection_order",
    ),
    "affordable_infill_rezoning": DocketTemplate(
        "affordable_infill_rezoning",
        "Affordable Infill Rezoning",
        "development",
        "POLYGON",
        {"activity": 3, "friction": 2, "exposure": 1, "trust": 1},
        {"activity": 1, "friction": 1},
        money_cost=18,
        mitigation_cost=9,
        expiration_policy="city_momentum",
        pressure_category="housing",
        preview="Starts an affordable infill buildout; capacity arrives only after construction, inspection, and occupancy.",
        inspect_hint="Covenant documents are complete. Affordability terms should be checked against the site plan.",
        target_rule="Select one or more districts to rezone for affordable infill.",
        stakeholder="housing_authority",
        denial_heat=2,
        failure_mode="zoning appeal",
        failure_effects={"friction": 4, "exposure": 1, "activity": -1},
        failure_base_chance=0.20,
        housing_effects={"affordability": 4},
        starts_chain_id="affordable_infill_buildout",
        project_step_id="rezoning",
        good_fit_types=("residential", "mercantile"),
        bad_fit_types=("natural", "industrial"),
        supporter_groups=("renters", "families", "workers", "developers"),
        concerned_groups=("homeowners", "commuters"),
        growth_groups=("renters", "families", "workers"),
        decline_groups=("homeowners",),
        contact_name="Housing Planning Office",
        spawn_archetype_id="affordable_infill_rezoning",
        scenario_tags=("housing_mandate",),
    ),
    "infill_construction_site": DocketTemplate(
        "infill_construction_site",
        "Infill Construction Mobilization",
        "development",
        "POINT",
        {"activity": 2, "friction": 2, "exposure": 2},
        {"friction": 1, "exposure": 1},
        money_cost=16,
        mitigation_cost=8,
        expires_after=2,
        expiration_policy="momentum_with_followup_risk",
        pressure_category="construction",
        preview="Starts work at the approved infill site. Temporary noise and fire exposure may increase.",
        inspect_hint="Construction schedule is mostly complete. Weather and subcontractor risks remain.",
        target_rule="Select exactly one district inside the approved infill project.",
        stakeholder="housing_authority",
        failure_mode="construction safety violation",
        failure_effects={"exposure": 5, "friction": 2, "activity": -1},
        failure_base_chance=0.24,
        hazard_effects={"noise": 1, "fire": 1},
        project_step_id="construction",
        supporter_groups=("developers", "workers", "renters"),
        concerned_groups=("elders", "homeowners", "families"),
        growth_groups=("workers", "developers"),
        contact_name="Construction Site Office",
        spawn_archetype_id="construction_site",
        scenario_tags=("housing_mandate",),
    ),
    "infill_inspection_order": DocketTemplate(
        "infill_inspection_order",
        "Infill Final Inspection",
        "compliance",
        "POINT",
        {"exposure": -4, "friction": -1},
        {"exposure": -1},
        money_cost=9,
        mitigation_cost=5,
        expiration_policy="mandatory_followup",
        pressure_category="inspection",
        preview="Runs the final inspection that clears or stalls the infill project.",
        inspect_hint="Inspection checklist is complete. Several items need field confirmation.",
        target_rule="Select exactly one district containing the infill project.",
        stakeholder="compliance_office",
        failure_mode="failed inspection",
        failure_effects={"exposure": 4, "friction": 3, "activity": -1},
        failure_base_chance=0.22,
        project_step_id="inspection",
        supporter_groups=("families", "renters", "civil_servants"),
        concerned_groups=("developers", "workers"),
        contact_name="Final Inspection Office",
        spawn_archetype_id="inspection_order",
        scenario_tags=("housing_mandate",),
    ),
    "occupancy_certificate": DocketTemplate(
        "occupancy_certificate",
        "Occupancy Certificate",
        "compliance",
        "POINT",
        {"activity": 2, "trust": 1, "exposure": -1},
        {"activity": 1},
        money_cost=7,
        mitigation_cost=4,
        expiration_policy="missed_window",
        pressure_category="housing",
        preview="Certifies occupancy. Housing capacity and service demand both increase.",
        inspect_hint="Addressing is complete. Utility and service readiness still need confirmation.",
        target_rule="Select exactly one district receiving occupancy.",
        stakeholder="housing_authority",
        failure_mode="delayed occupancy",
        failure_effects={"friction": 2, "exposure": 1, "activity": -1},
        failure_base_chance=0.12,
        housing_effects={"housing_capacity": 420, "population": 180, "affordability": 6},
        project_step_id="occupancy",
        supporter_groups=("renters", "families", "workers"),
        concerned_groups=("commuters", "homeowners"),
        growth_groups=("renters", "families", "workers"),
        contact_name="Occupancy Review Office",
        spawn_archetype_id="occupancy_certificate",
        scenario_tags=("housing_mandate",),
    ),
    "vendor_sanitation_complaint": DocketTemplate(
        "vendor_sanitation_complaint",
        "Vendor Sanitation Complaint",
        "incident",
        "POINT",
        {"friction": -1, "exposure": -2, "activity": -1},
        {"friction": -1},
        money_cost=7,
        mitigation_cost=5,
        expiration_policy="mandatory_followup",
        pressure_category="health",
        preview="A vendor-market nuisance issue has become a sanitation complaint.",
        inspect_hint="Complaint photos show queues, litter, and sanitation concerns.",
        target_rule="Select exactly one district hosting the vendor market.",
        stakeholder="public_health",
        denial_heat=2,
        ignore_heat=2,
        failure_mode="complaint escalation",
        failure_effects={"friction": 3, "exposure": 2},
        failure_base_chance=0.18,
        project_step_id="vendor_complaint",
        is_incident=True,
        supporter_groups=("families", "elders", "civil_servants"),
        concerned_groups=("vendors", "artists", "students"),
        contact_name="Sanitation Intake Office",
        spawn_archetype_id="vendor_sanitation_complaint",
    ),
}

TEMPLATES[MAINTENANCE_TEMPLATE_ID] = DocketTemplate(
    MAINTENANCE_TEMPLATE_ID,
    "Feature Maintenance Order",
    "maintenance",
    "POINT",
    {"exposure": -1, "friction": -1},
    {},
    money_cost=6,
    mitigation_cost=4,
    expiration_policy="mandatory_followup",
    pressure_category="maintenance",
    preview="An active support feature is due for maintenance. Issue or resolve it to close the follow-up.",
    inspect_hint="Maintenance records are short, but the condition score needs attention.",
    target_rule="Select the affected district or process the referenced support feature.",
    stakeholder="maintenance_office",
    denial_heat=1,
    ignore_heat=1,
    failure_mode="deferred maintenance",
    failure_effects={"exposure": 2, "friction": 1},
    failure_base_chance=0.08,
    is_enforcement=True,
    supporter_groups=("civil_servants", "families", "workers"),
    concerned_groups=("developers", "vendors"),
    contact_name="Maintenance Office",
    spawn_archetype_id="compliance_case",
)

DEMO_TEMPLATE_IDS = (
    "connector_corridor",
    "procession_route",
    "utility_expansion_trench",
    "natural_reserve_conversion",
    "mixed_use_rezoning",
    "child_development_park_annex",
    "street_vendor_compact",
    "business_license_fee_sweep",
    "contractor_renovation_waiver",
    "fire_budget_escalation",
    "public_art_museum_grant",
    "compliance_settlement_drive",
)
